### ISSUE TITLE
problem on src/diplomacy/adder_tutorial.md

### ISSUE THREAD

**Issue by YuanZheCN** [chipsalliance/rocket-chip#2823]
The code here is not right?
![image](https://user-images.githubusercontent.com/33506584/115282144-6ce69700-a17c-11eb-820b-99594b9b934a.png)

The buildOutput says that:
value io is not a member of freechips.rocketchip.diplomacy.LazyModuleImp
    when(monitor.module.io.error) {

**Comment by YuanZheCN** [comment]
setup.bst need to change

**Comment by zhuanhao-wu** [comment]
Hi @YuanZheCN, I'm facing the same issue and I cannot access `monitor.module.io.error`, I wonder if you could suggest a way to make it work?

**Comment by YingXiangLi10** [comment]
@zhuanhao-wu 
I encountered the same problem. But After I changed my chisel version, it worked. Maybe it only works using chisel 3.3.3. Here's my build.sbt
```
ThisBuild / scalaVersion     := "2.12.12"
ThisBuild / version          := "0.1.0"

lazy val root = (project in file("."))
  .settings(
    name := "chisel_template",
    libraryDependencies ++= Seq(
      "edu.berkeley.cs" %% "chisel3" % "3.3.3",
      "edu.berkeley.cs" %% "chiseltest" % "0.3.1" % "test",
      "edu.berkeley.cs" %% "rocketchip" % "1.2.+"

    ),
    scalacOptions ++= Seq(
      "-Xsource:2.11",
      "-language:reflectiveCalls",
      "-deprecation",
      "-feature",
      "-Xcheckinit"
    ),
    addCompilerPlugin("org.scalamacros" % "paradise" % "2.1.1" cross CrossVersion.full)
  )
```
